package space.linuxct.glyphworks.pipeline.runtime

import android.app.KeyguardManager
import android.content.Context
import android.hardware.Sensor
import android.hardware.SensorEvent
import android.hardware.SensorEventListener
import android.hardware.SensorManager
import android.media.AudioManager
import android.os.Handler
import android.os.Looper
import android.os.PowerManager
import space.linuxct.glyphworks.core.Ports
import space.linuxct.glyphworks.core.InclineMath
import space.linuxct.pipeline.*
import java.util.concurrent.ConcurrentHashMap

/** Demand-owned sensor snapshots, shared by every pipeline. No listener is acquired by a block. */
class PipelineInputs(private val app: Context, private val ports: Ports) : SensorEventListener {
    private val sensors = app.getSystemService(SensorManager::class.java)
    private val main = Handler(Looper.getMainLooper())
    private val samples = ConcurrentHashMap<Int, FloatArray>()
    private var requested = emptySet<String>()
    private var registered = emptySet<Int>()
    private var weatherActive = false
    private var batteryActive = false
    private var audioActive = false
    private var previous = emptyMap<String, Value>()
    private var lastSpeedAt = 0L
    private var lastBytes = -1L
    private var speed = 0L
    private var orientationCandidate: Int? = null
    private var orientationKnown = false
    private var orientationAt = 0L
    private var orientation = 0
    var snapshot: Map<String, Value> = emptyMap()
        private set

    @Synchronized fun demand(capabilities: Set<String>) {
        if ("compass" in requested && "compass" !in capabilities) ports.azimuth.setActive(false)
        if ("orientation" in requested && "orientation" !in capabilities) { ports.incline.setActive(false); ports.tilt.setActive(false) }
        requested = capabilities
        val types = buildSet {
            if ("accelerometer" in capabilities) add(Sensor.TYPE_ACCELEROMETER)
            if ("gyroscope" in capabilities) add(Sensor.TYPE_GYROSCOPE)
            if ("orientation" in capabilities) add(if (sensors?.getDefaultSensor(Sensor.TYPE_GRAVITY) != null) Sensor.TYPE_GRAVITY else Sensor.TYPE_ACCELEROMETER)
            if ("light" in capabilities) add(Sensor.TYPE_LIGHT)
            if ("proximity" in capabilities) add(Sensor.TYPE_PROXIMITY)
        }
        if (types != registered) {
            val generation = types
            registered = types
            main.post {
                synchronized(this) {
                    if (registered != generation) return@post
                    sensors?.unregisterListener(this)
                    samples.keys.retainAll(generation)
                    for (type in generation) sensors?.getDefaultSensor(type)?.let {
                        sensors.registerListener(this, it, SensorManager.SENSOR_DELAY_UI, main)
                    }
                }
            }
        }
        val needsAudio = "audio" in capabilities
        if (audioActive != needsAudio) { audioActive = needsAudio; ports.spectrum.setActive(needsAudio) }
        val needsBattery = "battery" in capabilities
        if (batteryActive != needsBattery) { batteryActive = needsBattery; ports.battery.setActive(needsBattery) }
        val needsWeather = "weather" in capabilities
        if (weatherActive != needsWeather) { weatherActive = needsWeather; ports.weather.setActive(needsWeather) }
        if (capabilities.isEmpty()) { previous = emptyMap(); snapshot = emptyMap(); lastBytes = -1; lastSpeedAt = 0; orientation = 0; orientationCandidate = null; orientationKnown = false; orientationAt = 0; samples.clear() }
    }
    fun close() = demand(emptySet())
    override fun onSensorChanged(event: SensorEvent) { samples[event.sensor.type] = event.values.copyOf() }
    override fun onAccuracyChanged(sensor: Sensor?, accuracy: Int) = Unit

    /** Run on the render scheduler. Calendar events are generated by the core interpreter. */
    @Synchronized fun poll(): List<PipelineEvent> {
        val now = ports.clock.elapsedMillis()
        val values = linkedMapOf<String, Value>()
        fun numeric(key: String, value: Number?) { values[key] = value?.let { Value.Number(it.toDouble(), InputCatalog.all.firstOrNull { spec -> spec.key == key }?.unit ?: UnitKind.SCALAR) } ?: Value.Unavailable() }
        if ("battery" in requested) {
            numeric("battery.level", ports.battery.levelPercent()); values["battery.charging"] = boolean(ports.battery.isCharging()); numeric("battery.watts", ports.battery.chargeWatts())
            values["battery.plugged"] = ports.battery.isPlugged()?.let(::boolean) ?: Value.Unavailable()
            values["battery.full"] = ports.battery.isFull()?.let(::boolean) ?: Value.Unavailable()
        }
        if ("audio" in requested) {
            values["music.playing"] = boolean(app.getSystemService(AudioManager::class.java)?.isMusicActive == true)
            val bands = ports.spectrum.bands(25)
            values["music.bands"] = bands?.let { Value.Items(it.map { v -> number(v) }) } ?: Value.Unavailable("Audio capture unavailable")
            numeric("music.energy", bands?.maxOrNull())
        }
        if ("notifications" in requested) numeric("notifications.count", ports.notifications.count())
        if ("screen" in requested) {
            values["screen.on"] = boolean(app.getSystemService(PowerManager::class.java)?.isInteractive == true)
            values["device.locked"] = boolean(app.getSystemService(KeyguardManager::class.java)?.isKeyguardLocked == true)
        }
        if ("connection" in requested) values["connection.state"] = text(ports.connectivity.state().name.lowercase())
        if ("speed" in requested) {
            if (lastBytes < 0 || now - lastSpeedAt >= 1000) {
                val total = ports.speed.totalRxBytes()
                if (lastBytes >= 0 && now > lastSpeedAt) speed = ((total - lastBytes).coerceAtLeast(0) * 1000 / (now - lastSpeedAt))
                lastBytes = total; lastSpeedAt = now
            }
            numeric("speed.bytesPerSecond", speed)
        }
        if ("compass" in requested) numeric("sensor.heading", ports.azimuth.azimuthDegrees())
        if ("location" in requested) {
            val location = ports.location.latLon(); numeric("location.latitude", location?.first); numeric("location.longitude", location?.second)
        }
        if ("weather" in requested) {
            val weather = ports.weather.snapshot(); numeric("weather.temperature", weather.temperatureC)
            values["weather.condition"] = weather.condition?.let { text(it.name.lowercase()) } ?: Value.Unavailable()
            values["weather.day"] = boolean(weather.isDay)
            values["weather.status"] = text(weather.status.name.lowercase())
        }
        fun vector(key: String, type: Int, unit: UnitKind) {
            values[key] = samples[type]?.takeIf { it.size >= 3 }?.let { Value.Vector(it[0].toDouble(), it[1].toDouble(), it[2].toDouble(), unit) } ?: Value.Unavailable("Sensor unavailable")
        }
        if ("accelerometer" in requested) vector("sensor.acceleration", Sensor.TYPE_ACCELEROMETER, UnitKind.METERS_PER_SECOND_SQUARED)
        if ("gyroscope" in requested) vector("sensor.gyroscope", Sensor.TYPE_GYROSCOPE, UnitKind.RADIANS_PER_SECOND)
        if ("light" in requested) numeric("sensor.light", samples[Sensor.TYPE_LIGHT]?.firstOrNull())
        if ("proximity" in requested) {
            val near = samples[Sensor.TYPE_PROXIMITY]?.firstOrNull()?.let { it < minOf(sensors?.getDefaultSensor(Sensor.TYPE_PROXIMITY)?.maximumRange ?: 5f, 5f) }
            values["sensor.proximity"] = near?.let(::boolean) ?: Value.Unavailable("Proximity sensor unavailable")
        }
        if ("orientation" in requested) {
            val gravity = samples[Sensor.TYPE_GRAVITY] ?: samples[Sensor.TYPE_ACCELEROMETER]
            vector("sensor.gravity", if (samples.containsKey(Sensor.TYPE_GRAVITY)) Sensor.TYPE_GRAVITY else Sensor.TYPE_ACCELEROMETER, UnitKind.METERS_PER_SECOND_SQUARED)
            if (gravity != null && gravity.size >= 3) {
                numeric("orientation.pitch", InclineMath.pitchDegrees(gravity[1], gravity[2])); numeric("orientation.roll", InclineMath.rollDegrees(gravity[0], gravity[2]))
                val z = gravity[2]
                val candidate = when { z < -7.5f -> -1; z > 7.5f -> 1; kotlin.math.abs(z) < 6f -> 0; else -> orientation }
                if (candidate != orientationCandidate) { orientationCandidate = candidate; orientationAt = now }
                if (now - orientationAt >= 200) { orientation = candidate; orientationKnown = true }
                values["orientation.faceDown"] = if (orientationKnown) boolean(orientation == -1) else Value.Unavailable()
                values["orientation.faceUp"] = if (orientationKnown) boolean(orientation == 1) else Value.Unavailable()
                values["orientation.edge"] = if (orientationKnown) boolean(orientation == 0) else Value.Unavailable()
            } else { values["orientation.faceDown"] = Value.Unavailable(); values["orientation.faceUp"] = Value.Unavailable(); values["orientation.edge"] = Value.Unavailable() }
        }
        snapshot = values
        val old = previous; previous = values.toMap()
        if (old.isEmpty()) return emptyList()
        val events = mutableListOf<PipelineEvent>()
        for ((prefix, event) in listOf("battery." to "battery.changed", "music." to "music.changed", "screen." to "screen.changed", "device." to "screen.changed", "orientation." to "orientation.changed", "sensor." to "sensor.changed", "weather." to "weather.changed", "connection." to "connection.changed")) {
            val changed = values.filter { (key, value) -> key.startsWith(prefix) && old[key] != value }
            if (changed.isNotEmpty()) events += PipelineEvent(event, changed, now)
        }
        val availability = values.filter { (key, value) -> (old[key] is Value.Unavailable) != (value is Value.Unavailable) }
        if (availability.isNotEmpty()) events += PipelineEvent("capability.changed", availability, now)
        return events.distinctBy { it.name }
    }
}
